import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Header from "./PageComponents/Header";
import { TodoStoreProvider } from "./providers/todo-store-provider";
import { AuthProvider } from "./contexts/auth-context";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <TodoStoreProvider>
          <AuthProvider>
            <div className="min-h-screen bg-linear-to-br from-slate-50 to-blue-50">
              {children}
            </div>
          </AuthProvider>
        </TodoStoreProvider>
      </body>
    </html>
  );
}
